---

server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sridharreddych/sree-spring-cloudconfig-wa-tolls
          search-paths:
          - 'station*'
          repos:
            perf:
              pattern:
                - "*/perf"
              uri: https://github.com/sridharreddych/sree-spring-cloudconfig-wa-tolls-perf
              search-paths:
                - 'station*'

  security:
    user:
      name: user
      password: user
 

    
